package tax.rules


import org.drools.domain.Employee;
import com.drools.service.EmployeeService

dialect "java" ;

global  EmployeeService employeeService;

rule "Starting rate limit "
when
$i: Employee(salary<=5000)
then
$i.setTax(0);

end

rule "Basic rate band "
when
$i: Employee(salary>5000 ,salary<=32000)
then
$i.setTax(20);

end

rule "Higher rate band "
when
$i: Employee(salary>32000, salary<=150000)
then
$i.setTax(40);

end


rule "Additional rate band"
when
$i: Employee( salary>150000)
then
$i.setTax(45);
end

rule "Populate Nino"
when
$i: Employee()
then
$i.setNino(employeeService.getNino($i.getEmpID())+"G");
end
